language: python
python:
- '2.7'
deploy:
  provider: s3
  access_key_id: AKIAINYJATAQAN5Y4RXQ
  secret_access_key:
    secure: 2Ra248MD/VWaAIzbQulR1lASp+GSwgpwfx7AK3jqRgCYzeb0bT3C3/1UIADOWu5C5x/tvZrG45WgiTHEevfjqiiUgUzVy0J5D7VKdJV7WimZXZw8dPHgcgaw8TnjPc5tEQoO4qw99r5l2j0jC9jK9qDU+jv2E5Y/hutPhlAKr02GecjjjHf9gOZWYOMlQILQ4dugYKsM4UJPwF+acNUBFYTSAgjSCmkCDSHOjyrFrqLSiTDc8thtZu+hG103nvIDdy4Dlju5UFjf2ZiVN3D4K0w9U3D3fby4ydhBT7GTnEJuxhZNUDuc/4o/YK5bRbw4rQ3gaWl3NEfCiM2G3VTPCN7InI+XYZwY8m/djLI4KLXgwIqNnTOem0h8kJgNlKJTemZVYqCgUeNtmJOepCljfp7WD/aOxaWWgWNXxU1HTJxFpGhgsCDrjpS84S7/SWoyct5gWKqh2mmBwg5lU9b887fxoZzCZiR+9kV1+vVLSD+LRP5YSdwwVOEZafVVeRfW5LF9WvofCmUJqRhcFjCIgtJhcmZjzsRx4dg/wn18loSA2OjF0K+MteopDJcrnaf1ywMXSEW7f/hqn8t1n08BIRn70YLr3S/8uGxNQgrzUMcE+eKHaem9nbhIAgP163OTvomZFJRzCSWQPGxUHiTvtBDJExK/Olj4KrvAI1mqc6U=
  bucket: web-module-deploy
  upload-dir: app
  acl: public_read
  on:
    repo: czczajka/web_module
  acces_key_id:
    secure: hTOygTEjBforpITzxRELq7z0O+pSoExVM7e2ybjepILohIJqZCn5CRW4063kZrgdpbcFGH2LsOkWwBqV2/gjhRsjKi6eScweuEiF1qyQfrewns8OV2iFpXXqwVKBQcfP6D1qu6bmLARMxzK0xnuZZ7aXfJ0oIrW2SEYkm8Qa6eGuxp7KKOiu3uAzG50gtiX8DVKu1ZyHi+cqprENWcPC7mxngOIR+vexGPyoH1slUEeBy5YTw+BQpcG5iL3EGD9iVZ4bF/+d9o4plUS120yLq8bmJkbN4S6LoU2iAFeVf00i1rUUwKjhdRRMODJTWsLr7t9Hq/1FkY9Ftw+C8B99fVuFleL5hH3BBZEYjDrr/hoRvchHxL6/kLFN1fDWqXB/T3FNXXe8MvxeSRomabtkRjIljijTUDBlohmTBdjQMl1+VfAMjpB1UAx+ngei/iGdOREJibOENfOfP+ba/dccblus+E3BxPuqYL3eqAtwMWb0LqmAKStPC+JmVIck2LO0RxLcDlyl8kPLfmWLhSaA1toH6vD3cw5FKvszIavwlWSNKBAP4BH7vIfVB+0cEcm0F2InnxyOgbCfPXVzaFNhfnG6OUiJKy1UNIPK7kB9PwIMDh1Z7Vn6ma299v9vL+mjlJ2lLAfptXwuqt/d+WljdjgopaFjuyDr9JKcARD6BHw=
